ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)calculator.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/calculator

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk