ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)send_response.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/server/send_response

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
