ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)validator.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/calculator/validator

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk