ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)entry-points-server.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/entry-points/server

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
