ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)


NAME			:= entry-points-server.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/entry-points/server

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
