ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)read_input.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/read_input

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
