ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)entry-points-client.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/entry-points/client

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
