ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

NAME			:= logger_system.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/logger_system

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk