ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)client_queue.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/server/client_queue

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
