ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)calculator_executor.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/calculator/calculator_executor

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk