ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)reply_message.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/server/reply_message

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk
