ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)send_message.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/client/send_message

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk