ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)client_core.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/client/client_core

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk