ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)logger-system.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/logger-system

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk