ROOT_DIRECTORY = $(shell git rev-parse --show-toplevel)

FOR_L			:= lib

NAME			:= $(FOR_L)receive_response.a
OBJECTS_DIR		:= $(ROOT_DIRECTORY)/objects/client/receive_response

include $(ROOT_DIRECTORY)/build_scheme/module-base-scheme.mk